# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
 config.vm.box = "debian/buster64"
 config.ssh.insert_key = false

config.vm.define "boundary", boundary: true do |server|
 server.vm.hostname = "boundary"
 server.vm.network "private_network", ip: "192.168.4.2"
end
config.vm.provision "ansible" do |ansible|
ansible.playbook = "boundary-server.yml"
end
end